version: '3'
services:
  llm:
    build: ./services/llm_service
    ports:
      - "8001:8000"
  sst:
    build: ./services/sst_service
    ports:
      - "8002:8000"
  tts:
    build: ./services/tts_service
    ports:
      - "8003:8000"

  retrieval:
    build: ./services/retrieval_service
    ports:
      - "8004:8000"
