apiVersion: apps/v1
kind: Deployment
metadata:
  name: tts-service
  namespace: ai-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tts
  template:
    metadata:
      labels:
        app: tts
    spec:
      containers:
        - name: tts
          image: your-dockerhub-username/tts-service:latest
          ports:
            - containerPort: 8000
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
