name: Build & Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          pip install requests
          python tests/test_latency.py

      - name: Build Docker images
        run: |
          docker build -t llm ./services/llm_service
