apiVersion: apps/v1
kind: Deployment
metadata:
  name: retrieval-service
  namespace: ai-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: retrieval
  template:
    metadata:
      labels:
        app: retrieval
    spec:
      containers:
        - name: retrieval
          image: your-dockerhub-username/retrieval-service:latest
          ports:
            - containerPort: 8000
